from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, JSON, Float, UniqueConstraint, Index
from sqlalchemy.orm import relationship
from pgvector.sqlalchemy import Vector
from .database import Base

class Role(Base):
    __tablename__ = "roles"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True, index=True, nullable=False)

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    password_hash = Column(String, nullable=False)
    role = Column(String, default="user")
    department = Column(String, nullable=True)
    workspace = Column(String, default="general", nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    sessions = relationship("ChatSession", back_populates="user")
    audit_logs = relationship("AuditLog", back_populates="user")

class ChatSession(Base):
    __tablename__ = "chat_sessions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    title = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="sessions")
    messages = relationship("Message", back_populates="session")

class Message(Base):
    __tablename__ = "messages"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("chat_sessions.id"), nullable=False)
    role = Column(String, nullable=False)
    content = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    session = relationship("ChatSession", back_populates="messages")

class DocumentChunk(Base):
    __tablename__ = "document_chunks"

    id = Column(Integer, primary_key=True, index=True)
    document_id = Column(String, nullable=False, index=True)
    filename = Column(String, nullable=False)
    page = Column(Integer, nullable=True)
    text = Column(Text, nullable=False)
    embedding = Column(Vector(768), nullable=True)
    workspace = Column(String, default="general", nullable=False)
    ocr_confidence = Column(Float, nullable=True)
    chunk_source = Column(String, default="text", nullable=True)  # 'text' | 'ocr' | 'vision'
    created_at = Column(DateTime, default=datetime.utcnow)

class AuditLog(Base):
    __tablename__ = "audit_logs"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    action = Column(String, index=True, nullable=False)
    resource = Column(String, nullable=True)
    details = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="audit_logs")


class DocumentStatus(Base):
    """Tracks async processing state for every uploaded document."""
    __tablename__ = "document_status"

    id = Column(Integer, primary_key=True, index=True)
    document_id = Column(String, unique=True, nullable=False, index=True)
    filename = Column(String, nullable=False)
    file_hash = Column(String, nullable=True, index=True)
    workspace = Column(String, default="general", nullable=False)
    uploader_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    # "processing" | "completed" | "failed"
    status = Column(String, nullable=False, default="processing")
    error_message = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class Workspace(Base):
    """Tracks named workspaces/collections for the Knowledge Base."""
    __tablename__ = "workspaces"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True, index=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

class Agent(Base):
    """Stores predefined agent workflows/prompts."""
    __tablename__ = "agents"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False, unique=True)
    description = Column(String, nullable=False)
    prompt_template = Column(Text, nullable=False)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

class Deliverable(Base):
    """Tracks documents generated by the agent (e.g. Word, Excel, PDF, PPTX)."""
    __tablename__ = "deliverables"

    id = Column(Integer, primary_key=True, index=True)
    filename = Column(String, nullable=False)
    file_type = Column(String, nullable=False)
    generated_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    download_path = Column(String, nullable=False)


class DocumentAcl(Base):
    """
    Per-document access-control list (ACL).

    Semantics
    ---------
    * If a document has NO rows in this table  → visible to everyone with
      workspace access (default / backward-compatible behaviour).
    * If a document has ANY rows in this table → only users whose user_id
      matches OR whose role matches one of those rows may access it.
      Admins always bypass ACL.

    Exactly one of user_id / role must be non-NULL per row.
    """
    __tablename__ = "document_acl"

    id = Column(Integer, primary_key=True, index=True)
    document_id = Column(String, nullable=False, index=True)
    # Grant to a specific user …
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    # … or to an entire role (e.g. "manager", "engineer")
    role = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        # Prevent duplicate grants: one row per (document, user) and one per (document, role)
        UniqueConstraint("document_id", "user_id", name="uq_acl_doc_user"),
        UniqueConstraint("document_id", "role", name="uq_acl_doc_role"),
        Index("ix_acl_document_id", "document_id"),
    )

class PendingAction(Base):
    """
    Stores a pending tool action that requires human approval.
    """
    __tablename__ = "pending_actions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    session_id = Column(Integer, ForeignKey("chat_sessions.id"), nullable=True) # Optional link to chat
    tool = Column(String, nullable=False)
    arguments = Column(JSON, nullable=False)
    # "pending" | "approved" | "rejected" | "modified"
    status = Column(String, nullable=False, default="pending")
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Optional relations
    user = relationship("User")


